### ISSUE TITLE
Update Package to newest

### ISSUE THREAD

**Issue by JonahJ** [iron-meteor/iron-layout#17]
Behind a corporate proxy so can't use meteor add directly, this repo is behind?

Get following error when installed manually with all of the iron-router packages. 

```
TypeError: Object [object Object] has no method '_setLookupHost'
    at [object Object].Controller (packages/iron:controller/lib/controller.js:25:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:14:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
```

FYI changed code in package.js to 

```
Package.describe({
  summary: 'Dynamic layouts which enable rendering dynamic templates into regions on a page.',
  version: '1.0.8', //1.0.0-pre3
  git: 'https://github.com/eventedmind/iron-layout',
  name: 'iron:layout'
});
```

**Comment by bogdanrn** [comment]
Same problem :+1: 

```
TypeError: Object [object Object] has no method '_setLookupHost'
    at [object Object].Controller (packages/iron_controller/lib/controller.js:25:1)
    at new Controller.extend.constructor (packages/iron_router/lib/route_controller.js:14:1)
    at [object Object].ctor (packages/iron_core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron_router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron_router/lib/router_server.js:39:1)
    at Object.router (packages/iron_router/lib/router.js:15:1)
    at next 
```

**Comment by zachariahtimothy** [comment]
I just upgraded to 1.0.11 and received the same error on a working app.

**Comment by chrisbutler** [comment]
working on a fix for this right now

**Comment by zachariahtimothy** [comment]
Awesome thank you, it looks like it has something to do with oAuth in WebApp.

**Comment by chrisbutler** [comment]
@zachariahtimothy are you able to revert to 1.0.10?

**Comment by zachariahtimothy** [comment]
@chrisbutler  Yes I tried 1.0.11 -> 1.0.8 (which I was on before the upgrade) and none of them work, same error thrown.

**Comment by bogdanrn** [comment]
Related https://github.com/iron-meteor/iron-router/issues/1452

**Comment by pfafman** [comment]
Someone correct me if I am wrong but the resolver is set up so that requesting 1.0.n will give you the latest in the 1.0.x series.  For only the patch number has changed.  You can only downgrade if the first (major) or second (minor) numbers are different.  Or am I confused?

**Comment by bogdanrn** [comment]
as @floodpeak commmented on https://github.com/iron-meteor/iron-router/issues/1452

you can use this to downgrate to a working version

```
meteor add iron:router@=1.0.10
meteor add iron:core@=1.0.8
```

**Comment by pfafman** [comment]
Thanks

**Comment by nooitaf** [comment]
@bogdanrn works, thanks :)
